- hosts: terraform-ansible
  tasks:
  - name: Instalando python3 e virtualenv
    apt: 
      pkg:
      - python3 
      - virtualenv 
      update_cache: yes
    become: yes
  - name: Instalando dependencia com pip  
    pip:
      virtualenv: /home/ubuntu/venv
      name: 
      - django
      - djangorestframework
  - name: Iniciando projeto
    shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup .'
  - name: Alterando hosts do settings
    lineinfile: 
      path: /home/ubuntu/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes    